name: qt515-core20
base: core20 
version: '5.15.4'
summary: Qt5.15 runtime for core20
description: |
  This snap is to be consumed by various Qt apps which uses Qt 5.15 as their runtime.
  Qt provides C++ classes and QML types for rendering GUI.

grade: stable 
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    run-on: amd64

package-repositories:
  - type: apt
    formats: [deb]
    components: [main]
    suites: [focal]
    key-id: C65D51784EDC19A871DBDBB710C56D0DE9977759
    url: https://ppa.launchpadcontent.net/beineri/opt-qt-5.15.4-focal/ubuntu
    

slots: 
  qt515-core20:
    interface: content
    read: 
      - /

parts:
  qt515:
    plugin: nil
    stage-packages:
    # Packages form internal repo
      - adwaita-icon-theme
      - dmz-cursor-theme
      - fontconfig
      - gnome-themes-standard
      - freeglut3
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libglib2.0-bin
      - libglu1-mesa
      - libgtk2.0-0
      - libice6
      - libxkbcommon0
      - light-themes
      - locales-all
      - shared-mime-info
      - ttf-ubuntu-font-family
      - xdg-user-dirs
      
    # Desktop integration
    # (note: do not add anypackage that pulls Qt dependency from official repo)
      - libfcitx-gclient1
      - libfcitx-utils0
      - fcitx-module-dbus
      - fcitx
      - ibus-gtk3
      - libibus-1.0-5
      - libcanberra-gtk3-module
      - glib-networking

    # Qt modules from opt/qt515
      - qt515base
      - qt515imageformats
      - qt515multimedia
      - qt515svg
      - qt515webchannel
      - qt515webengine
      - qt515x11extras
      - qt515wayland
      - qt515tools
      # Qt QML types
      - qt515graphicaleffects
      - qt515declarative
      - qt515quickcontrols
      - qt515quickcontrols2
      
    # Multimedia  
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad # many gst plugins lives here
      - gstreamer1.0-alsa
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-libav
      - gstreamer1.0-x
      - gstreamer1.0-gl
     
    # Additional Packages required by consumers
      - mpv
      - ffmpeg
      - socat
      - wget
      - xclip
      - libtag1v5
      - python3.9
      
  # adwaita-qt widget style
  adwaita-qt:
    after:
      - qt515
    build-snaps:
      - cmake/3.17/stable
    plugin: cmake
    source: https://github.com/keshavbhatt/adwaita-qt.git
    build-packages:
      - build-essential
      - qt515base
      - qt515x11extras
      - libgl1-mesa-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb1-dev
    override-build: |
      set -eux

      QT_BASE_DIR=/opt/qt515
      export QTDIR=$QT_BASE_DIR
      export PATH=$QT_BASE_DIR/bin:$PATH
      export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/$SNAPCRAFT_ARCH_TRIPLET:$QT_BASE_DIR/lib:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      export PKG_CONFIG_PATH=$QT_BASE_DIR/lib/pkgconfig:${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}

      INSTALL_PATH=${SNAPCRAFT_PART_INSTALL}/opt/qt515/
      mkdir -p ${INSTALL_PATH}

      mkdir -p build
      cd build
      cmake -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_PATH} -DCMAKE_BUILD_TYPE=Release $SNAPCRAFT_PART_SRC
      make -j 4
      make install

      mkdir -p ${INSTALL_PATH}/plugins/styles/
      cp -r /opt/qt515/plugins/styles/adwaita.so ${INSTALL_PATH}/plugins/styles/adwaita.so
    prime:
      - -${INSTALL_PATH}/share/doc
      - -${INSTALL_PATH}/include
      - -${INSTALL_PATH}lib/cmake
      - -${INSTALL_PATH}/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake
      - -${INSTALL_PATH}/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig

  cleanup:
    after:
      - adwaita-qt
    plugin: nil
    override-prime: |
      
      set -eux

      # Qt opt/qt515 runtime cleanup ========================================

      for QT_CRUFT in doc examples include; do
        rm -rf $SNAPCRAFT_PRIME/opt/qt515/$QT_CRUFT
      done

      rm -rf $SNAPCRAFT_PRIME/opt/qt515/lib/metatypes/

      rm -rf $SNAPCRAFT_PRIME/opt/qt515/lib/cmake/

      rm -rf $SNAPCRAFT_PRIME/opt/qt515/mkspecs/

      find $SNAPCRAFT_PRIME/opt/qt515/ -name "*.la" -type f -delete

      find $SNAPCRAFT_PRIME/opt/qt515/ -name "*.a" -type f -delete

      find $SNAPCRAFT_PRIME/opt/qt515/ -name "*.cmake" -type f -delete

      find $SNAPCRAFT_PRIME/opt/qt515/ -name "*.prl" -type f -delete

      find $SNAPCRAFT_PRIME/opt/qt515/ -name "*.pc" -type f -delete

      find $SNAPCRAFT_PRIME/opt/qt515/ -type d -empty -delete

      # System cleanup ========================================================

      for CRUFT in bug lintian man doc; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done

      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
